[package]
name = "lobo"
version = "0.1.0"
edition = "2021"
publish = false # To prevent accidental publish on crates.io

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

nokhwa = {version = "0.10", git = "https://github.com/chriamue/nokhwa", branch = "feature/input-libcamera", features = ["input-opencv"]}
#nokhwa = {version = "0.9.4", features = ["input-msmf"]}


[target.'cfg(windows)'.dependencies]
onnxruntime-sys = "0.0.12"
onnxruntime = "0.0.12"


[target.'cfg(unix)'.dependencies]
onnxruntime-sys = "0.0.14"
onnxruntime = "0.0.14"

camera_capture = "0.5.0"
image = "0.24.0"