[package]
name = "lobo"
version = "0.1.0"
edition = "2021"
authors = ["Shubhamai"]
publish = false # To prevent accidental publish on crates.io

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv =  "0.74.1"
gnuplot = "0.0.37"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.16.0"
rand = "0.8.5"

# ndarray version changed to "0.15.3" in onnxruntime cargo.toml
onnxruntime = {path = "onnxruntime-rs/onnxruntime"}
onnxruntime-sys = {path = "onnxruntime-rs/onnxruntime-sys"}

[dependencies.nokhwa]
version = "0.9.4"
features = ["input-msmf", "input-v4l"]

[profile.release]
debug = 0
strip = "symbols"
overflow-checks = false
panic = "abort"
opt-level = 3
lto = "thin"