[package]
name = "lobo"
version = "0.1.0"
edition = "2021"
publish = false # To prevent accidental publish on crates.io

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv =  "0.74.1"
gnuplot = "0.0.37"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.16.0"
rand = "0.8.5"

# ndarray version changed to "0.15.3" in onnxruntime cargo.toml
onnxruntime = {path = "onnxruntime-rs/onnxruntime"}
onnxruntime-sys = {path = "onnxruntime-rs/onnxruntime-sys"}


# 0.0.14 seems to be giving error on windows
#[target.'cfg(windows)'.dependencies]
#onnxruntime-sys = "0.0.14"
#onnxruntime = "0.0.14"

#[target.'cfg(unix)'.dependencies]
#onnxruntime-sys = "0.0.14"
#onnxruntime = "0.0.14"

[dependencies.nokhwa]
version = "0.9.4"
features = ["input-msmf", "input-v4l"]