name: Bug Report
description: File a bug report
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: "# Bug Report Form"
  - type: textarea
    id: logs
    attributes:
      label: Logs
      placeholder: |
        *  INFO StableView::network: Version 0.1.0 on windows
        *  INFO StableView::network: Sending data to 127.0.0.1 on port 4242
      description: Please paste the contents from the logs.txt (located in C:/Users/USERNAME/AppData/Roaming/StableView/data) into the field.
      render: StringTemplate
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is and what happened.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
        ...
      description: We need to know how you encountered the bug to properly troubleshoot the issue.
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References (optional)
      description: If applicable, add screenshots or videos to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: misc
    attributes:
      label: Additional info (optional)
      description: Add any other context about the problem here. Was this working before? When did the issue start occurring?
    validations:
      required: false
  - type: input
    id: discord
    attributes:
      label: Discord Username (optional)
      description: You may optionally provide your discord username, so that we may contact you directly about the issue.
      placeholder: ex. username#1234
    validations:
      required: false
