name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

# Linters inspired from here: https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
jobs:
  test:
    name: Formatting, Test, Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v2
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Ubuntu Dependencies
        run: sudo apt-get install libopencv-dev clang libclang-dev clang
      - run: rustup component add rustfmt clippy
      - name : Format
        run : cargo fmt --all -- --check
      - name : Clippy
        run: cargo clippy  -- -D warnings
      - name: Build 
        run: cargo build --verbose
      - name: Run tests 
        run: cargo test --verbose
