name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Cargo Cache
        uses: Swatinem/rust-cache@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install WiX
        run: dotnet tool install --global wix

      - name: Install WiX
        run: |
          cargo install cargo-wix

      - name: Installing Opencv, LLVM
        run: choco install llvm opencv
      
      - name: Test
        env:
           OPENCV_LINK_LIBS: opencv_world460
           OPENCV_INCLUDE_PATHS: C:\tools\opencv\build\include
           OPENCV_LINK_PATHS: C:\tools\opencv\build\x64\vc15\lib
        run: cargo test --release
