name: Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Cargo Cache
        uses: Swatinem/rust-cache@v2
      - name: Install WiX
        run: |
          nuget install WiX
          cargo install cargo-wix
      - name: Installing Opencv, LLVM
        run: choco install llvm opencv
      #- name: Test
      #  env:
      #    OPENCV_LINK_LIBS: opencv_world460
      #    OPENCV_INCLUDE_PATHS: C:\tools\opencv\build\include
      #    OPENCV_LINK_PATHS: C:\tools\opencv\build\x64\vc15\lib
      #  run: cargo test --release
      - name: Build
        env:
          OPENCV_LINK_LIBS: opencv_world460
          OPENCV_INCLUDE_PATHS: C:\tools\opencv\build\include
          OPENCV_LINK_PATHS: C:\tools\opencv\build\x64\vc15\lib
        run: cargo build --release
      - name: Crate msi installer
        env:
          OPENCV_LINK_LIBS: opencv_world460
          OPENCV_INCLUDE_PATHS: C:\tools\opencv\build\include
          OPENCV_LINK_PATHS: C:\tools\opencv\build\x64\vc15\lib
        run: cargo wix --nocapture
      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: StableView.msi
          path: target/wix/*.msi
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/wix/*.msi
