name: Release

on :
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
  workflow_dispatch : 

jobs:

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Install WiX
        run : |
          nuget install WiX
          cargo install cargo-wix
      - name : Installing Opencv, LLVM
        run : choco install llvm opencv
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Crate msi installer
        run: cargo wix
